version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=catering'
    restart: always

  app:
    image: 'kuzd4niil/demo_tomcat:v2'
    container_name: 'java-app'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/catering'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=123456'
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always